### ISSUE TITLE
Make it simple to download the UI and the map

### ISSUE THREAD

**Issue by defreez** [RaiderSoft/semantic-godot#5]

**Comment by thompsop1sou** [comment]
For the UI, I think we will need to have *user_interface.tscn* and at least also *info_label.tscn* (since we need to make new instances of that label during runtime). If we want to keep the press-enter-to-send functionality, we'll also need *NewMsgEdit.cs*. I should be able to rework *user_interface.tscn* so that it doesn't depend on any external files, except perhaps *NewMsgEdit.cs*. We could have the tutorial-user add that script during the tutorial to make sure there aren't any broken paths.

For the map, we should just need *map.tscn* and *forest_bridge.jpg*. Since *map.tscn* depends on accessing *forest_bridge.jpg*, it will probably be necessary to have the tutorial-user add that image to the map scene during the tutorial (again, to make sure there aren't any broken paths).

**Comment by defreez** [comment]
What you have for the map looks good, but I am thinking of moving it to the top of Movement and Collisions to go with the east/west arguing theme. 

It would become 

Part 1: Map and Level
Part 2: The Troll Scene, with the NPC scene from simple chat npcs as the starting point
Part 3: The Player Scene

**Comment by defreez** [comment]
Map part was fixed and we have separate issues for sections now. Closing.
